# Temporary comment to bust GitHub Actions cache
name: Fetch Stripe AARs

on:
  workflow_dispatch:

jobs:
  fetch-aars:
    runs-on: ubuntu-latest

    steps:
      - name: Create minimal Gradle project
        run: |
          mkdir fetch-aar && cd fetch-aar
          echo "rootProject.name='fetch-aar'" > settings.gradle
          cat > build.gradle <<'EOF'
          plugins { id 'java-library' }
          repositories {
            mavenCentral()
            maven {
              url "https://artifacts.stripe.com/maven"
              credentials {
                username = System.getenv("STRIPE_MAVEN_USERNAME")
                password = System.getenv("STRIPE_MAVEN_PASSWORD")
              }
            }
          }
          configurations { stripeAars }
          dependencies {
            stripeAars "com.stripe.stripeterminal:stripeterminal-core:4.5.0"
            stripeAars "com.stripe.stripeterminal:stripeterminal-external:4.5.0"
            stripeAars "com.stripe.stripeterminal:stripeterminal-taptopay:4.5.0"
          }
          task copyAars(type: Copy) {
            from configurations.stripeAars
            into "$buildDir/stripe-aars"
          }
          build.dependsOn(copyAars)
          EOF

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Fetch AARs
        working-directory: fetch-aar
        env:
          STRIPE_MAVEN_USERNAME: ${{ secrets.STRIPE_MAVEN_USERNAME }}
          STRIPE_MAVEN_PASSWORD: ${{ secrets.STRIPE_MAVEN_PASSWORD }}
        run: ./gradlew clean build

      - name: Upload AARs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: stripe-aars
          path: fetch-aar/build/stripe-aars/
